# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Verify

on:
  issue_comment:
    types:
    - created

jobs:
  verify:
    name: Verify
    if: contains(github.event.comment.html_url, '/pull/')
#    if: github.event.head_commit.message == 'CI'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
      fail-fast: false
    steps:
    - name: output message
      run: echo ${{ github.event.head_commit.message }}
    - name: Checkout source codes
      uses: actions/checkout@v2
