# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on:
  #  issue_comment:
  pull_request_comment:
    types:
    - created
name: Verify
jobs:
  verify:
    name: Verify
    if: github.event.head_commit.message == 'CI'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
